


MAX_CONSECUTIVE_FAILURES = 4
MAX_SURF_STREAK = 4
MAX_RECOMMENDED_STREAK = 2


SEARCH_MODIFIERS = [
    "tutorial", "how to", "best", "review", "explained",
    "for beginners", "tips", "guide", "vs", "top 10",
]


SHORT_CYCLE_PROBABILITY = 0.3
SHORT_CYCLE_RANGE = (5, 15)
LONG_CYCLE_RANGE = (20, 50)
BREAK_SKIP_PROBABILITY = 0.2
BREAK_MIN_REMAINING_S = 120
BREAK_FRACTION_RANGE = (0.05, 0.10)
BREAK_CAP_RANGE = (3 * 60, 7 * 60)


FATIGUE_CURVE_EXPONENT = 0.8
FATIGUE_NOISE_STD = 0.02
FATIGUE_MODE_SWITCH_TO_A_THRESHOLD = 0.6
FATIGUE_MODE_SWITCH_TO_B_THRESHOLD = 0.4
FATIGUE_MODE_SWITCH_TO_A_PROBABILITY = 0.5
FATIGUE_MODE_SWITCH_TO_B_PROBABILITY = 0.3
LOCK_TASK_MODE = True


WATCH_LONG_FALLBACK = (90, 900)
WATCH_FOCUSED_FALLBACK = (60, 600)
SURF_VIDEO_RANGE = (30, 90)
CLICK_RECOMMENDED_FALLBACK_A = (120, 600)
CLICK_RECOMMENDED_FALLBACK_B = (90, 320)
FIRST_EVAL_RANGE = (35, 75)
QUICK_EXIT_PROBABILITY = 0.01
SPEED_CHANGE_PROBABILITY = 0.4
SEEK_FORWARD_PROBABILITY = 0.3
SPEED_CHOICES = [1.25, 1.5]
SEEK_CHOICES = [10, 15, 30]
SURF_GO_BACK_PROBABILITY = 0.55


CONTINUE_CURRENT_VIDEO_PROBABILITY = 0.85
CONTINUE_CURRENT_VIDEO_MIN_REMAINING_S = 120.0
CONTINUE_CURRENT_VIDEO_FALLBACK = (180.0, 480.0)
WATCH_ACTION_MIN_REMAINING_S = 45.0


MICRO_SCROLL_PROBABILITY = 0.10
MICRO_WIGGLE_PROBABILITY = 0.05
MICRO_PAUSE_PROBABILITY = 0.03
WATCH_CHUNK_RANGE = (3.0, 12.0)
COMMENT_REFOLLOW_DEPTH_TRIGGER = 3
COMMENT_REFOLLOW_BASE_PROBABILITY = 0.55
COMMENT_REFOLLOW_STEP_PROBABILITY = 0.15
COMMENT_REFOLLOW_MAX_PROBABILITY = 0.90


FULL_WATCH_CHANCE_SHORT_A = 0.35
FULL_WATCH_CHANCE_MID_A = 0.20
FULL_WATCH_CHANCE_LONG_A = 0.10
FULL_WATCH_CHANCE_SHORT_B = 0.20
FULL_WATCH_CHANCE_MID_B = 0.10
FULL_WATCH_CHANCE_LONG_B = 0.05


COVERAGE_CAP_WATCH_LONG = (220.0, 520.0)
COVERAGE_CAP_WATCH_FOCUSED = (150.0, 360.0)
COVERAGE_CAP_CLICK_RECOMMENDED = (120.0, 300.0)
COVERAGE_CAP_DEFAULT = (120.0, 260.0)
COVERAGE_SEARCH_OVERHEAD_S = 30.0
COVERAGE_CAP_MIN_S = 35.0
COVERAGE_CAP_BUDGET_FRACTION = 0.75


REALISM_MIN_WATCH_S = 180.0
REALISM_MIN_WATCH_AFTER_COVERAGE_S = 240.0
REALISM_MIN_WATCH_TRIGGER_REMAINING_S = 300.0
REALISM_MULTI_TOPIC_MIN_WATCH_S = 90.0
REALISM_MULTI_TOPIC_MAX_WATCH_S = 135.0
REALISM_MULTI_TOPIC_BUDGET_FRACTION = 0.45


VIDEO_PACE_TARGET_MIN_PER_COMPLETED = 6.5
VIDEO_PACE_GRACE_COMPLETED = 1.5
VIDEO_PACE_PRE_COVERAGE_MIN_ELAPSED_MIN = 10.0
VIDEO_PACE_PRE_COVERAGE_MIN_COMPLETED = 3
VIDEO_PACE_PRE_COVERAGE_PENDING_BONUS_PER_TOPIC = 0.35
VIDEO_PACE_PRE_COVERAGE_PENDING_BONUS_CAP = 1.4


SEARCH_PRESSURE_THRESHOLDS = [
    (90, 0.80),
    (180, 0.60),
    (360, 0.42),
]
SEARCH_PRESSURE_DEFAULT = 0.25
SEARCH_PRESSURE_STYLE_WEIGHT = 0.20
SEARCH_PRESSURE_CLAMP = (0.10, 0.85)
SEARCH_MIN_ACTIONS_BETWEEN_OPTIONAL_SEARCHES = 2


ENTERTAINMENT_FATIGUE_MEDIUM = 0.6
ENTERTAINMENT_FATIGUE_HIGH = 0.8
TASK_FATIGUE_MEDIUM = 0.5
TASK_FATIGUE_HIGH = 0.8


IDLE_NORMAL_RANGE = (2, 8)
IDLE_FATIGUED_RANGE = (5, 15)
IDLE_FATIGUE_THRESHOLD = 0.6


AD_CAPTURE_SCREENSHOT_COUNT = 5
AD_CAPTURE_SCREENSHOT_INTERVAL_MS = 1000
AD_CAPTURE_SCREENSHOT_PREROLL_TIMEOUT_S = 1.5
AD_CAPTURE_SCREENSHOT_FALLBACK_DELAY_S = 0.35
AD_CAPTURE_LANDING_TIMEOUT_MS = 15_000
AD_CAPTURE_VIDEO_DOWNLOAD_TIMEOUT_S = 30
AD_CAPTURE_MAX_ASSET_SIZE_BYTES = 10 * 1024 * 1024
AD_CAPTURE_MAX_TOTAL_ASSETS = 200
AD_CAPTURE_RECORDING_START_TIMEOUT_S = 6.0
AD_CAPTURE_RECORDING_RETRY_INTERVAL_S = 0.35
AD_CAPTURE_RECORDER_WARMUP_MS = 0
AD_COMPLETION_OVERFLOW_MAX_S = 30.0

LIVE_PROGRESS_SYNC_INTERVAL_S = 3.0


ORCHESTRATION_MIN_WINDOW_MINUTES = 180
ORCHESTRATION_ACTIVE_BUDGET_FRACTION = (0.35, 0.60)
ORCHESTRATION_ACTIVE_CHUNK_SECONDS = (20 * 60, 55 * 60)
ORCHESTRATION_BREAK_SECONDS = (10 * 60, 90 * 60)
ORCHESTRATION_MIN_ACTIVE_REMAINDER_SECONDS = 4 * 60
ORCHESTRATION_MIN_NEXT_CHUNK_SECONDS = 8 * 60
ORCHESTRATION_RUN_LOCK_TTL_SECONDS = 4 * 60 * 60
